name: Shell Script Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        shell: [bash]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux jq coreutils
        
    - name: Set up BATS testing environment
      run: |
        chmod +x .github/scripts/setup-bats.sh
        ./.github/scripts/setup-bats.sh
        
    - name: Make scripts executable
      run: |
        # Make all shell scripts in hooks directory executable
        find hooks/ -name "*.sh" -exec chmod +x {} \;
        chmod +x test/*.sh
        
    - name: Run test setup
      run: |
        cd test
        ./setup_test.sh
        
    - name: Run all tests
      run: |
        cd test
        ./run_tests.sh --verbose
        
    - name: Test with different shell configurations
      run: |
        # Test with minimal PATH
        export PATH="/usr/bin:/bin"
        cd test
        ./run_tests.sh --test "should handle.*not available" --verbose
        
    - name: Cleanup test environment
      if: always()
      run: |
        # Kill any remaining tmux sessions
        tmux list-sessions 2>/dev/null | grep "test-claude" | cut -d: -f1 | xargs -I {} tmux kill-session -t {} 2>/dev/null || true
        # Clean up test files
        rm -rf ./test-tmp-* 2>/dev/null || true
        rm -f /tmp/gemini-review* 2>/dev/null || true

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
    - name: Run ShellCheck on shell scripts
      run: |
        # Check test files with error level only (allow warnings for test scripts)
        find test -name "*.sh" | xargs shellcheck -S error || true
        # Check hook files with warnings only (don't fail on warnings)
        find hooks -name "*.sh" | xargs shellcheck -S error || true
        # Check other shell scripts strictly (root level scripts)
        find . -name "*.sh" -not -path "./test/*" -not -path "./hooks/*" -not -path "./test-tmp-*" -not -path "./.git/*" | xargs shellcheck -S warning || true
        
    - name: Run ShellCheck on bats files
      run: |
        # Only check our own bats files, exclude submodule test files (error level only)
        find test -name "*.bats" -not -path "test/test_helper/*" | xargs shellcheck -S error || true
        
    - name: Check script executability
      run: |
        [ -x hooks/gemini-review-hook.sh ] || (echo "hooks/gemini-review-hook.sh is not executable" && exit 1)
        [ -x test/run_tests.sh ] || (echo "test/run_tests.sh is not executable" && exit 1)
        [ -x test/setup_test.sh ] || (echo "test/setup_test.sh is not executable" && exit 1)

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Run bandit security scan
      run: |
        # Install bandit for shell script security scanning
        pip install bandit
        
        # Check for common security issues in shell scripts
        find . -name "*.sh" -not -path "./test-tmp-*" -not -path "./.git/*" -exec grep -l "eval\|exec\|system\|rm -rf" {} \; | while read -r file; do
          echo "Security review needed for: $file"
          grep -n "eval\|exec\|system\|rm -rf" "$file" || true
        done
        
    - name: Check for hardcoded secrets
      run: |
        # Check for potential hardcoded secrets
        find . -name "*.sh" -not -path "./test-tmp-*" -not -path "./.git/*" -exec grep -i "password\|secret\|key\|token" {} \; | grep -v "# " | head -10 || true
        
    - name: Verify file permissions
      run: |
        # Check that script files have appropriate permissions
        find . -name "*.sh" -not -path "./test-tmp-*" -not -path "./.git/*" -exec ls -la {} \;

  compatibility:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux jq coreutils
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install tmux jq coreutils bash
        
        # Add modern Bash to PATH and verify
        echo "BASH_PATH=$(brew --prefix)/bin/bash" >> $GITHUB_ENV
        echo "$(brew --prefix)/bin/bash --version"
        
    - name: Set up BATS testing environment
      run: |
        chmod +x .github/scripts/setup-bats.sh
        ./.github/scripts/setup-bats.sh
        
    - name: Test script compatibility
      run: |
        cd test
        chmod +x setup_test.sh run_tests.sh
        
        # Configure for macOS with modern Bash
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          # Ensure we're using modern Bash for tests
          export PATH="$(brew --prefix)/bin:$PATH"
          echo "Using Bash version: $(bash --version | head -1)"
          
          # Run setup with modern Bash
          bash ./setup_test.sh
        else
          ./setup_test.sh
        fi
        
    - name: Run basic compatibility tests
      run: |
        cd test
        
        # Configure for macOS with modern Bash
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          export PATH="$(brew --prefix)/bin:$PATH"
          echo "Running tests with modern Bash: $(bash --version | head -1)"
          
          # Run tests with modern Bash
          bash ./run_tests.sh --test "help.*display" --verbose
          bash ./run_tests.sh --test "should fail when no session name" --verbose
        else
          # Run a subset of tests to verify compatibility
          ./run_tests.sh --test "help.*display" --verbose
          ./run_tests.sh --test "should fail when no session name" --verbose
        fi
